### ISSUE TITLE
Add textstat_select()

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1153]
Here is a prototype
```r
period <- ifelse(docvars(data_corpus_inaugural, "Year") < 1945, "pre-war", "post-war")
mt <- dfm(corpus_subset(data_corpus_inaugural, period == "post-war"))
key <- textstat_keyness(mt, target = "2017-Trump")

textstat_select <- function(x, pattern, selection = c("keep", "remove"),
                              valuetype = c("glob", "regex", "fixed"), case_insensitive = TRUE) {
    
    
    selection <- match.arg(selection)
    valuetype <- match.arg(valuetype)
    
    id <- unlist(quanteda:::regex2id(pattern, rownames(x), valuetype, case_insensitive))

    if (selection == 'keep') {
        x[id ,]
    } else {
        x[id * -1,]
    }
}

textstat_select(key, '*ing')
#                   chi2            p n_target n_reference
# transferring 25.545694 4.320292e-07        2           0
# winning      16.059340 6.138807e-05        2           1
# bring         6.701594 9.632677e-03        4          20
# listening     5.352849 2.068844e-02        1           0
# allowing      5.352849 2.068844e-02        1           0
# refusing      5.352849 2.068844e-02        1           0
```

**Comment by kbenoit** [comment]
I'd rather add a `pad = TRUE` argument to `dfm_select()` to combine the non-selected features into `""`, and then run `textstat_keyness()`. I don't like the idea of starting to spawn tokens-type manipulation functions into the downstream objects (such as textstat results).

Otherwise we could consider having a common phrase-type parent class of which keyness results and collocations (for instance) are child classes, and write some manipulation functions for them.

But I strongly prefer the first option, as this is how we did collocations selection for instance (before applying `textstat_collocations()`. This also vastly improves the performance of the textstat function since it does not need to work as hard.

**Comment by koheiw** [comment]
This is basically to subset data.frame by `row.names` for human inspection by glob patterns, because I find it is tedious to do make selection with `stringi::stri_detect_regex()`. 

We can instead just define `subset.textstat_keyness()` and `subset.textstat_collocations()`.

**Comment by kbenoit** [comment]
Very good solution. By keeping these internal, we have access to the functionality without cluttering up the function list or polluting the grammar. (Since base R is already a toxic waste dump, grammatically.)

**Comment by koheiw** [comment]
Next question is why `textstat_collocations` have no `row.names`? I think it is look more consistent have `row.names` in all `textstat_*` objects.

**Comment by kbenoit** [comment]
I agree it's inconsistent. But probably the better direction would be to deprecate the row names for data.frame objects, since data.table does not use them, and nor does the increasingly popular tibble format.

**Comment by kbenoit** [comment]
http://www.perfectlyrandom.org/2015/06/16/never-trust-the-row-names-of-a-dataframe-in-R/

**Comment by koheiw** [comment]
`textstat_lexdiv()` returns data.frame only when `drop = FALSE` (default is `TRUE`). We should remove `drop` argument.

**Comment by kbenoit** [comment]
Agreed, textstat outputs ought to be all data.frames. Removing the drop argument might break some things but we can fix them. (This is why we have ~90% codecov!)

**Comment by kbenoit** [comment]
Current state of `textstat_*` functions:

| function | output object | row.names | dimension(s) | name |
|:--------|:---------|:------|:------|:-----|
| `textstat_collocations` | data.frame | no | collocation | `collocation` |
| `textstat_frequency` | data.frame | no | feature | `feature` |
| `textstat_keyness` | data.frame | yes | feature | - |
| `textstat_lexdiv` | data.frame | yes | document | - |
| `textstat_dist` | dist | yes | feature or document | n/a |
| `textstat_simil` | simil/dist | yes | feature or document | n/a |
| `textstat_readability` | data.frame | yes | document | - |

This suggests that `keyness`, `lexdiv`, and `readability` should:
- remove the row.names and use a new column called either `feature` or `document` depending on the function (or the `margin` value if applicable); and 
- not have a `drop` argument, so that they always return a data.frame.

`dist` and `simil` are special matrix-like objects so should remain unchanged.

**Comment by koheiw** [comment]
Use of `filter()` on `textstat` makes **quanteda** looks like **tidytext**. We should avoid this at all cost, because it is not only confusing for users but also shameful for us. We should follow our naming system inspired by **stringi**.

**Comment by kbenoit** [comment]
Moved to [**quanteda.tidy**](https://github.com/quanteda/quanteda.tidy).
