### ISSUE TITLE
Chaging min_count to percentile when  < 1.0?

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1181]
`dfm_trim()` takes a fraction for `min_count` but it is hardly useful, because normalized frequency of words are very small, and it is really difficult to set a threshold like `min_count = 0.0001`. 

```
> colMeans(dfm_weight(dfmt, 'prop'))
               moscow                 trump                  said                  sure               whether 
         4.681466e-04          1.809751e-04          4.610098e-03          3.180712e-05          4.869455e-04 
                joint            us-russian         cybersecurity                 group             discussed 
         1.580790e-04          0.000000e+00          7.027506e-06          8.929641e-04          1.607924e-05 
              russian             president              vladimir                 putin                 might 
         3.366126e-04          1.563445e-04          0.000000e+00          8.911385e-06          2.685655e-04 
               really                   set                facing               overall            opposition 
         4.259691e-04          4.438829e-04          6.528476e-05          1.330071e-04          1.436127e-04 
                 idea                 moved                  back               working                  huge 
         6.577164e-04          5.672176e-05          1.017178e-03          7.629350e-04          1.788385e-04
```
It becomes if a fractional `min_count` is interpreted as percentile: i.e. `dfm_trim(min_count = 0.1)` means discard bottom 10% of words.

**Comment by kbenoit** [comment]
The reason for making it a proportion instead of a percentile is that this creates an unambiguous difference between counts (`min_count` > 1) and relative amounts (0 < `min_count` < 1). This would not be the case with percentages.

Our users will just have to divide by 100 if they want to input a percentile!

**Comment by koheiw** [comment]
I know the difference, but dividing by 100 does not work. If we want to keep the top 10% of the features, for example, we have to set `min_count = 0.0002388872`.

```r
corp <- data_corpus_irishbudget2010
dfmt <- dfm(corp, group = rep('all', ndoc(corp)))

freq <- colSums(dfmt)
freq_prop <- colSums(dfm_weight(dfmt, 'prop'))

dfm_trim(dfmt, min_count = quantile(freq, 0.9)) # min_count = 7
dfm_trim(dfmt, min_count = quantile(freq_prop, 0.9)) # min_count = 0.0002388872
```
We can find a good threshold like 5 or 10 for `min_count`, but who can find 1 / 5000 as a threshold without using `quantile()`? So I am proposing to do that automatically in `dfm_trim()` in the following way:
```r
if (min_count < 1)
     min_count <- quantile(colSums(x), min_count)
```

**Comment by kbenoit** [comment]
I totally agree, and thought that's how it behaved already. If not, I think it's just a bug in the way I originally programme this. Let's change it to the way you suggest above.

**Comment by kbenoit** [comment]
The other option would be to add a new argument which is `min_pct` etc. Should a “count”only really be a count?

**Comment by koheiw** [comment]
I think it is better to add `min_pct`, because `dfm_trim` would not work without it when a dfm is already weighted to `prop`.

**Comment by kbenoit** [comment]
OK, I've investigated this more, now I more correctly understand the issue here.

First, having thought about it, I don't favour adding more parameters for percentage thresholds, since that adds four new parameters that also have strange interactions with existing parameters, and still does not resolve the indeterminacy with respect to trimming a weighted dfm (which is what this issue is about). 

For a weighted dfm, `dfm_trim()` should operate differently. We should basically either disallow the proportion values, and issue a note or warning that the "count" is interpreted as a value rather than an integer, when the weightTf is not a count.

Here's some other things I uncovered that need fixing:

```r
(testdfm <- dfm(c("a a a a b b", "a b b c")))
# Document-feature matrix of: 2 documents, 2 features (0% sparse).
# 2 x 2 sparse Matrix of class "dfm"
#        features
# docs    a b c
#   text1 4 2 0 
#   text2 1 2 1

## BUG
dfm_trim(testdfm, min_count = 6)
# Error in dfm_trim.dfm(testdfm, min_count = 6) : 
#     max_count must be >= min_count 

## OK
dfm_trim(testdfm, min_count = 5)
# Document-feature matrix of: 2 documents, 1 feature (0% sparse).
# 2 x 1 sparse Matrix of class "dfm"
#        features
# docs    a
#   text1 4
#   text2 1

## BUG: should be the same
sum(testdfm)
# [1] 10
identical(
    dfm_trim(testdfm, min_count = .5),
    dfm_trim(testdfm, min_count = 5)
)      
# [1] FALSE

## OK
dfm_trim(testdfm, max_count = 4)
# Document-feature matrix of: 2 documents, 2 features (25% sparse).
# 2 x 2 sparse Matrix of class "dfm"
#        features
# docs    b c
#   text1 2 0
#   text2 2 1

## BUG: should be the same
identical(
    dfm_trim(testdfm, max_count = 4),
    dfm_trim(testdfm, max_count = .4)
)
# [1] FALSE

## OK
dfm_trim(testdfm, min_count = 2, max_count = 4)
# Document-feature matrix of: 2 documents, 1 feature (0% sparse).
# 2 x 1 sparse Matrix of class "dfm"
#        features
# docs    b
#   text1 2
#   text2 2
```

We should also test the same for `min/max_docfreq`.

**Comment by koheiw** [comment]
How about adding a new argument `as_percentile = TRUE/FALSE`? When it is `TRUE`, `min_count` and `max_count` are interpreted as percentile.

**Comment by kbenoit** [comment]
That won't solve the units issue completely, since the issue here is what to do when a dfm has been weighted. If it's log weights, or tf-idf, then the percentile approach does not mean what people think.

Let's fix it so it works as it should currently (which it does not - see above) and add a warning when `dfm_trim()` is applied to any dfm whose weightTf slot is not "count".
