### ISSUE TITLE
Add ability to create identical compound tokens

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1227]
Currently, there is no easy way to compound new tokens object in the same way as existing one without original patterns. This becomes a problem when we apply a model that was trained on compounded tokens to a new tokens (or a DFM created from it).

This can be done easily if `tokens_compound()` records compounding patters as an attribute of its output, and also takes a tokens object as a `pattern`. This is a conceptually similar `dfm_select()`  that takes a DFM as a pattern to make feature set identical.

**Comment by kbenoit** [comment]
I have always been slightly uncomfortable about the usage of a dfm as a “pattern” in `dfm_select()`, since it violates the general rules about the pattern/valuetype/case_insensitive combination. 

What if we created a helper function to extract the compounds/features/etc as a “pattern”, and the argument to pattern would then be wrapped inside that? This the usage consistent since extractor/wrapper would extract from the object what is a consistent pattern type (list or vector).

We could do this for `dfm_select()` too but keep the old behavior while not advertising it further.

**Comment by koheiw** [comment]
I felt strange with a DFM as a pattern n `dfm_select`(), but I just got used to it. I am OK to change the behavior in the way you are thinking. for `dfm_select()`, `featname()` is the extractor. We need to create `compounds()` or something similar for compounded tokens objects.

**Comment by koheiw** [comment]
We can achieve this simply by `tokens_compound(toks, phrase(types(toks_old)))` if the concatenator of `toks_old` is the whitespace. If we want to make this easier, `types()` should return the concatenator as an attribute, and `phrase()` should use it to make a list.

**Comment by kbenoit** [comment]
I'm not sure I fully understand this issue. The 2 year old comments are obsolete since `dfm_select()` no longer takes a dfm for `pattern`. So please remind me what is "this" again? (as in "We can achieve this...")

**Comment by koheiw** [comment]
We can record patterns used in `tokens_compound()` in the object meta, but it can be done manually too. I am fine to close this issue.
