### ISSUE TITLE
Confusing colors on the textplot_keyness plot.

### ISSUE THREAD

**Issue by brousseauj** [quanteda/quanteda#1233]
when plotting keyness, the colors used are red and blue, blue being the target. The target bars are blue but the text is red. Why the difference? Also, can we pass ggplot arguments to textplot to alter the style? 

![image](https://user-images.githubusercontent.com/17204759/36166620-f0d8b584-10a7-11e8-9c93-f7bed482daa9.png)

**Comment by kbenoit** [comment]
Thanks for the feedback. @koheiw and I are in the process of fixing this plot, and will add to #1211 the issue about the words. I think they should be black by default. Also, when there just two classes, we will have the legend label read the name of the reference document, rather than the generic "Reference".

Yes, you should be able to change the plot using **ggplot2** `+` additions.

**Comment by brousseauj** [comment]
Awesome! Off topic, thank you for building this package. It's truly powerful and has been the basis of building out my companies text analytics platform! I will be posting all the code in my GitHub!

**Comment by kbenoit** [comment]
Thanks! I look forward to seeing that. Feel free to leave a testimonial at #461.
