### ISSUE TITLE
Add marginal frequencies of the original dfm to a fcm.

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1262]
We do not `dfm_weight` but not `fcm_weight()`. We need marginal frequency of original dfm to weight fcm properly by, for example, PMI. This is also related to #1260 

This is only to add a verctor as an attribute, but `fcm_select()` should keep the vector in the same length the a dimension of a fcm.

**Comment by kbenoit** [comment]
Feature co-occurrence matrices cannot be weighted in the same way as dfms, because the window determines the context of co-occurrence and this will not be related to the global feature accounts across documents. Weighting by would have to be within window context, not document context.

Maybe I am missing something ... do you have an example application in mind?

**Comment by koheiw** [comment]
What I want is PMI calcualted as following:
```r
dfmt <- dfm(c('a a a', 'a b', 'a a b c c d e'))
margin <- colSums(dfmt)

fcmt <- fcm(dfmt)
fcmt <- fcmt / sum(fcmt)
fcmt / tcrossprod(margin  / sum(margin))
```
but I am actually not sure how to calculate PMI when window is used.

**Comment by kbenoit** [comment]
For any weighting of a window-context fcm, a weighting approach would need to use the window as the "document" and use the margins of the window for computing proportions etc. I've not seen this done anywhere though, so this might be better avoided in trying to define a scheme for `fcm_weight()`.

**Comment by kbenoit** [comment]
Added the storage of original feature marginals in 96d01a554c81d78f225c110abcc168c9bb2a9ab5. How you use this for weights is a different issue - I don't favour creating an `fcm_weight()` until I see some literature suggesting that/how this is useful.
