### ISSUE TITLE
Selection argument in textstat_simil/dist is not working with interger index

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1266]
```r
d1 <- dfm(c("a b c", "a b c d"))
d2 <- dfm(letters[1:6])
dtest <- dfm_select(d1, d2)


textstat_simil(dtest, margin = 'features', selection = 'a')
textstat_simil(dtest, margin = 'features', selection = 1) # error

textstat_simil(dtest, margin = 'documents', selection = 'text1')
textstat_simil(dtest, margin = 'documents', selection = 1) # error

textstat_dist(dtest, margin = 'features', selection = 'a')
textstat_dist(dtest, margin = 'features', selection = 1) # error

textstat_dist(dtest, margin = 'documents', selection = 'text1')
textstat_dist(dtest, margin = 'documents', selection = 1) # error

```

**Comment by koheiw** [comment]
Probably this is not a bug but design. The documentation actually says if `selection` is a numeric vector, it is compares with `x`. However, taking column or raw index for `selection` is a more natural behavior.

**Comment by kbenoit** [comment]
By design it should take a numeric index too, so it's a bug. Adding the ability to select from a numeric  index should be implemented. I suggest we add logical selection too.

**Comment by koheiw** [comment]
If it takes numeric index, there will be an ambiguity whether the input to `selection` is an index for `x` or an object for which similarity will be calculated. One solution would be to restrict such objects to be a dfm.

**Comment by kbenoit** [comment]
I agree that we cannot both allow an integer index _and_ an object supplied as a direct numeric for comparison with x. I think the original idea was to supply an object like the `y` in `proxy::similar()`. But since it's called `selection`, it should be a valid index for the `margin` specified, and this means character, integer, or logical. So for consistency, we should drop the direct supply of an object whose similarity will be computed, and make this argument behave as its name suggests.
