### ISSUE TITLE
Where should docnames come from?

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1293]
`?corups` says "Names to be assigned to the texts. Defaults to the names of the character vector (if any); doc_id for a data.frame", but It does not seem to be the case.
```r
data <- data.frame(text = c('a b c', 'b c d'), stringsAsFactors = FALSE)
data$doc_id <- c('doc1', 'doc2')

corp <- corpus(data)
docnames(corp) # [1] "text1" "text2"

rownames(data) <- c('doc1', 'doc2')
corp <- corpus(data)
docnames(corp) # [1] "doc1" "doc2"
```
It this a bug or an error in documentation?

**Comment by kbenoit** [comment]
I just noticed this today myself, independently!

I think it's not a bug. We set `docid_field = NULL` in the signature of `corpus.data.frame()`, instead of `docid_field = "doc_id"`, because we cannot be sure that there is a "doc_id" variable.

What do you think is the preferred behaviour?
```r
library("testthat")
test_that("corpus constructor uses doc_id", {
    skip_if_not_installed("readtext")
    tempd <- tempdir()
    cat("Text one.", file = paste(tempd, "doc_1.txt", sep = "/"))
    cat("Text two.", file = paste(tempd, "doc_2.txt", sep = "/"))
    
    require("readtext")
    rt <- readtext(paste0(tempd, "/*.txt"))
    crp <- corpus(rt)
    
    expect_identical(names(rt), c("doc_id", "text"))

    # this works
    expect_identical(rt$doc_id, docnames(corpus(rt, docid_field = "doc_id")))
    
    # THIS FAILS
    expect_identical(docnames(crp), rt$doc_id)
})
```

**Comment by koheiw** [comment]
Document identifier is called `doc_id` in **readtext** but `docnames` in **quanteda**. I think **readtext** should return them in a column called 'docnames' or in rownames. I also get confused by `corpus.data.frame`, that does not have `docnames` argument. 

To make things less confusing, how about: 

* If a data.frame has rownames, `corpus()` should use them as document names, unless overwritten by `docnames` argument. 
* If neither the data.frame has rownames nor `docnames` are given, `corpus()` name documents text1, text2, text3...

**Comment by kbenoit** [comment]
Yes, it can be a bit confusing, and this is why we have the different S3 methods for `corpus()` (as opposed to pretty much all of the other functions, which have a single signature for every object class).

For **readtext**, we have done with the TIF names, thinking that this would be independent from **quanteda**.  We could make the default `docid_field = "doc_id"` and make it clear that this default to `paste0(quanteda_options("base_docname"), 1:nrow(x))` if there is no field called `doc_id`.

I think originally in an early version of `corpus.data.frame()`, it has a signature like
```r
corpus(x, docid_field = NULL, docnames = if (is.null(docid_field)) rownames(x), ...)
```
but that was even more confusing to all but the most expert R users.

So I suggest that we only change the default to 
```r
corpus(x, docid_field = "doc_id", ...)
```
and make it clear in the documentation that this will use the quanteda defaults if there is no "doc_id" field. That means that it will be straightforward to construct readtext objects in one step. 

We should test whether an argument is supplied for `docid_field`, however, since if one _is_ supplied _and_ does not exist, we should throw an error. If _not supplied_ and `"doc_id"` does not exist, we will use the `quanteda_options("base_docname")` instead.

**Comment by Dominique22** [comment]
My corpus is a set of 10 files of texts (.txt) of ten  politicians. Each file has the name of the politician.
My code is 
corp_data <- readtext(paste0("C:/Users/Dom/Documents/corp/*.txt"), docvarsfrom = "filenames", dvsep = "_", docvarnames="names",encoding = "UTF-8")
pol_corp <- corpus(corp_data)

**Comment by kbenoit** [comment]
@Dominique22 it's impossible to tell without seeing more about the `corp_data` object or knowing something about your filenames. But
```r
pol_corp <- corpus(corp_data, docid_field = "doc_id")
```
should work.

**Comment by Dominique22** [comment]
it works !
thank you

**Comment by TimBMK** [comment]
Sorry I'm a little late to the party, but is there a way to force `corpus()` to fall back to generating doc IDs from rownames even if there is a "doc_id" variable present in the data? Setting `NULL` or `NA` does not do the trick and the documentation is a little unclear as to how the fallback option can be triggered. Since `docid_field` expects a column name, simply generating doc names on the fly does not seem to work, either.

The purpose of this is using `corpus()` in a larger function where the behaviour of `corpus()` changes when the user input's ID variable is named "doc_id". Rather than checking for this case and renaming the variable, I would like to set a fixed behaviour on the `coprus()` function level.

**Comment by kbenoit** [comment]
You can always override docnames by 1) specifying a `docnames` vector in `corpus()`, e.g.

``` r
library("quanteda")
#> Package version: 3.3.1
#> Unicode version: 14.0
#> ICU version: 71.1
#> Parallel computing: 10 of 10 threads used.
#> See https://quanteda.io for tutorials and examples.

mytxt <- c(one = "a b c", two = "d e f")

# element names become docnames
corpus(mytxt)
#> Corpus consisting of 2 documents.
#> one :
#> "a b c"
#> 
#> two :
#> "d e f"

# docnames are serial numbers
corpus(mytxt, docnames = seq_along(mytxt))
#> Corpus consisting of 2 documents.
#> 1 :
#> "a b c"
#> 
#> 2 :
#> "d e f"
```

<sup>Created on 2023-06-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

or 2) you can assign them after creating the corpus using 

``` r
corp <- corpus(mytxt)
docnames(corp) <- seq_along(corp)
corp
#> Corpus consisting of 2 documents.
#> 1 :
#> "a b c"
#> 
#> 2 :
#> "d e f"
```
