### ISSUE TITLE
Suppress warning message from textplot_wordcloud()

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1303]
The page is flooded by warning messages: https://docs.quanteda.io/reference/textplot_wordcloud.html
They are from the original source code, so we can change that easily.

**Comment by kbenoit** [comment]
I just pushed a slightly different Rd page for `textplot_wordcloud()` to `master`, which should render as HTML without the warnings. (It increases the minimum term frequency requirement to reduce the wordcloud size.)

If that does not work, we can use `suppressWarnings()`. 

I will let you rebuild the **pkgdown** site since I am not sure what the revised workflow is for that, since we changed the way this is done from #1284.
