### ISSUE TITLE
Extract specific documents of a corpus

### ISSUE THREAD

**Issue by bbo2adwuff** [quanteda/quanteda#1423]
How to manually select certain documents in a corpus? Let's say I'd like to select document 2:3 from an existing corpus. `my_corpus[2:3]` just returns the text fields instead of a corpus with 2 documents.

Do I just overlook something and there is already an easy way to do that? If not, this is basically a feature request.

A workaround would be to assign IDs with `1:ndoc(my_corpus)` as `docvars` and then use `corpus_subset`.

In my opinion, next to `corpus_subset`, a feature similar to base `[` (i.e. extract) could be useful.

Or maybe it could be useful to add something along these lines to `corpus_subset.corpus`:
```r
    if(
        class(subset) == 'logical' |
        class(subset) == 'integer'
    ){
        r <- subset
    }
```

Then `corpus_subset` would take input similar to base `[`. In my example:
```r
corpus_subset(x, 2:3)
corpus_subset(x, c(FALSE, TRUE, TRUE, FALSE))
```

**Comment by bbo2adwuff** [comment]
Sorry for not realizing earlier, but standard evaluation actually works with the logical vector in my example at the bottom...

Well, I could close this issue now because I can subset using standard evaluation. But I leave it open, because I think that others might find it more intuitive to try `[` for subsetting.

I leave it up to you to close it.

**Comment by kbenoit** [comment]
The issue here is that a corpus is not ordered, so indexing using integer ranges is not reliable. (The current implementation of the indexing for texts has this problem.) Better to use `corpus_subset()` on supplied values or docvar values.

The evaluation of `corpus_subset()` works exactly similar to `base::subset()`, but with NSE on docvars (or logical conditions involving doctors) and standard evaluation on any supplied (logical) vector.
