### ISSUE TITLE
website timing out

### ISSUE THREAD

**Issue by sarepal** [quanteda/quanteda#1437]
## Other questions

The main website (quanteda.io) has been timing out for several days now. Do you know when it will be accessible again?

**Comment by stefan-mueller** [comment]
We have established a new website for the Quanteda Initiative (https://quanteda.org) which replaces and extends the former main website at https://quanteda.io. 

https://quanteda.io now contains the documentation of the **quanteda** package. Since last week, the [other QI packages](https://quanteda.org/projects/) also have their own html documentations.

**Comment by kbenoit** [comment]
Everything should be working now, except https://github.com/quanteda/quanteda.org/issues/33.
