### ISSUE TITLE
fcm(ordered = TRUE) is not working properly

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1461]
I expect ordered fcm to be asymmetric, but it is not. Also we should set `tri = FALSE` automatically when `ordered = TRUE`.
```r
> fcm(c("a b c", "a b c"), "window", window = 2, ordered = TRUE)
Feature co-occurrence matrix of: 3 by 3 features.
3 x 3 sparse Matrix of class "fcm"
        features
features a b c
       a 0 2 2
       b 0 0 2
       c 0 0 0
> fcm(c("a b c", "a b c"), "window", window = 2, ordered = TRUE, tri = FALSE)
Feature co-occurrence matrix of: 3 by 3 features.
3 x 3 sparse Matrix of class "fcm"
        features
features a b c
       a 0 2 2
       b 0 0 2
       c 0 0 0
```

**Comment by kbenoit** [comment]
Not sure I understand here, since both of those matrices are in fact asymmetric, and correct for what we intended for `ordered = TRUE`.

The lower triangle is all 0 because no column feature in the lower part comes after its row feature. If we add a new feature to the second document, it does show up correctly (and asymmetrically):
```r
> fcm(c("a b c", "d a b c"), "window", window = 2, ordered = TRUE)
Feature co-occurrence matrix of: 4 by 4 features.
4 x 4 sparse Matrix of class "fcm"
        features
features a b c d
       a 0 2 2 0
       b 0 0 2 0
       c 0 0 0 0
       d 1 1 0 0
```

The documentation already states
> `tri` if `TRUE` return only upper triangle (including diagonal). Ignored if `ordered = TRUE`.
