### ISSUE TITLE
Inconsistency between remove_url and remove_twitter

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1477]
In relation to #1465, I think that there is an inconsistency between `remove_url` and `remove_twitter`. Why whole "@koheiw" and "#quanteda" are not remove, while "http://google.com" is deleted?
```r
> tokens("http://google.com aaa", remove_url = TRUE)
tokens from 1 document.
text1 :
[1] "aaa"

> tokens("@koheiw #quanteda bbb", remove_punct = TRUE, remove_twitter = TRUE)
tokens from 1 document.
text1 :
[1] "koheiw"   "quanteda" "bbb"
```
I expect the second to be
```r
[1] "bbb"
```

**Comment by koheiw** [comment]
We could add `remove_tag` to delete whole tags, and deprecate `remove_twitter`.

**Comment by amatsuo** [comment]
In my understanding, the use of `remove_twitter` is for analyzing hashtags (and sometimes people's names) along with normal nouns. For example, we can combine `#boris` and `boris` into one. For that purpose, the current implementation is useful. 

I don't see much reason to have a functionality of removing hashtags and mentions entirely, as these are quite useful for many purposes and removing them with `tokens_remove` is super easy.

**Comment by kbenoit** [comment]
The name is misleading but the function is sound: it means preserve the special Twitter punctuation characters when `remove_punct = TRUE, remove_twitter = FALSE`. @amatsuo and I relied on this a lot in the Brexit study to keep #brexit and @strongerin (e.g.) as hashtags and usernames while removing other punctuation.

We used the `remove_twitter` to keep the name consistent, so that everything could start with `remove_...` and also not to have a longer compound argument name such as `remove_twitter_punct`.

In your example to keep only "bbb" then it's easiest to do it separately:

```r
> tokens("@koheiw #quanteda bbb") %>%
      tokens_remove(pattern = "^[#@].+$", valuetype = "regex")
tokens from 1 document.
text1 :
[1] "bbb"

```

**Comment by koheiw** [comment]
I am doing `tokens_remove(pattern = "^[#@].+$", valuetype = "regex")` currently. 

In order to make `what = "word"` and `what = "fasterword"` consistent (#1465) without loosing flexibility, we have to distinguish between keeping "@" and "#" with following word ("kohei" or "quanteda") and (2) removing "@" and "#". `remove_twitter` actually does only 1 and `remove_punct` does 2. We can call it  `separate_twitter_punct` (and make it independent of `remove_punct`).

This behavior is similar to current `remove_hyphens = FALSE`, which should be called `separate_hyphens = TRUE`:
```r
> tokens("a-b c d", remove_hyphens = TRUE)
tokens from 1 document.
text1 :
[1] "a" "-" "b" "c" "d"

> tokens("a-b c d", remove_hyphens = FALSE)
tokens from 1 document.
text1 :
[1] "a-b" "c"   "d"

> tokens("a-b c d", remove_hyphens = TRUE, remove_punct = TRUE)
tokens from 1 document.
text1 :
[1] "a" "b" "c" "d"
```
