### ISSUE TITLE
Allow additional arguments for as.dictionary()

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/quanteda#1562]
## Describe the bug

Currently, `as.dictionary()` does not allow adding any additional arguments from `dictionary()`. This means, for instance, that all terms are lowercased which might not be suitable for all dictionary analyses.

Maybe we add `...` to `as.dictionary()` or is there a more elegant solution?

## Reproducible code

```r
library(quanteda)
#> Package version: 1.3.18
#> Parallel computing: 2 of 12 threads used.
#> See https://quanteda.io for tutorials and examples.
#> 
#> Attaching package: 'quanteda'
#> The following object is masked from 'package:utils':
#> 
#>     View

df <- data.frame(
    word = c("A", "B"),
    sentiment = c("positive", "negative"))

as.dictionary(df)
#> Dictionary object with 2 key entries.
#> - [negative]:
#>   - b
#> - [positive]:
#>   - a

as.dictionary(df, tolower = FALSE)
#> Error in as.dictionary(df, tolower = FALSE): unused argument (tolower = FALSE)
```

## Expected behavior

```r
as.dictionary2 <- function(x, ...) {
    if (!all(c("word", "sentiment") %in% names(x)))
        stop("data.frame must contain word and sentiment columns")
    if ("lexicon" %in% names(x) && length(unique(x[["lexicon"]])) > 1)
        warning("multiple values found in a \'lexicon\' column; ",
                "you may be mixing different dictionaries")
    if (all(is.na(x[["sentiment"]])))
        stop("sentiment values are missing")
    dictionary(with(x, split(as.character(word), as.character(sentiment))), ...)
}

as.dictionary2(df, tolower = FALSE)
#> Dictionary object with 2 key entries.
#> - [negative]:
#>   - B
#> - [positive]:
#>   - A
```

**Comment by koheiw** [comment]
Makes sense to me. Why don't you issue a PR?

**Comment by kbenoit** [comment]
`as.dictionary()` only works at the moment on **tidytext** data.frame dictionaries. The idea behind this (versus `dictionary()`) was to create a coercion method for "foreign" dictionary objects. 

If we pass additional arguments, we should specify them explicitly, since we wouldn't want the `file` for instance, and would only want `format` if we add additional formats (in addition to **tidytext** dictionaries) and wanted to allow the user to force the type in case our brilliant code is unable to detect this automatically.

Also since the import objects will already be R objects, I don't think we should support the encoding argument. Foreign objects should have sorted this out in their own formats.

So how about:
```r
as.dictionary(x, format = c("tidytext"), separator = " ", tolower = FALSE)
```
which implies no change to the existing behaviour but adds options that allow case conversion and explicit change to future formats.

**Comment by kbenoit** [comment]
No I don't think we need to unexport it, we already check whether it works with the **tidytext**-compliant data.frame, so it will currently only work with that.

**Comment by koheiw** [comment]
I see
