### ISSUE TITLE
Tokenizing on stopwords

### ISSUE THREAD

**Issue by adamlauretig** [quanteda/quanteda#1600]
## Requested feature

First of all, thanks for the fantastic package. I don't know if you've seen [this](https://github.com/dperezrada/evidence-tools/tree/master/nlp/keywords2vec), but the authors propose finding "meaningful" keywords by splitting tokens on punctuation and stopwords. Would it make sense to implement this in `quanteda::tokens()`? A toy example using `stringr::str_split()` is below

Please explain the feature you want clearly and concisely. If possible, please add example output.
```r
# an example
library(quanteda)
library(data.table)
library(stringr)
d <- quanteda::data_corpus_inaugural
tmp_data <- data.table::data.table(txts = d$documents$texts, yr = d$documents$Year, 
  president = paste(d$documents$FirstName, d$documents$President))
tmp_data <- as.data.table(tmp_data)
stops_split <- paste0(
  paste0("\\s", stopwords("en"), "\\s", collapse = "|"), "[[:punct:]]", 
  collapse = "|")
splits_on_stops <- str_split(string = tmp_data$txts, pattern = stops_split)

```

## Use case

This would be another option for tokenizing, that seems to promise relevant keywords, rather than having to manually create ngrams.

## Additional context

Please add any other information about the feature request.

**Comment by kbenoit** [comment]
Our way to do this would be:
1.  `tokens()`
2. `textstat_collocations()` to score multiword expressions (MWE)
3. `tokens_compound()` on the selected collocations to convert the MWEs to tokens and
4. then form an fcm and then apply word2vec on the unigrams and "meaningful" MWEs.

Doing this step mechanically at the tokenization stage is not our preferred method because:
* it's not tokenization but rather a selection or scoring of tokens, which is something different
* the separation of steps allows some (much needed) exercise of human judgement as to what threshold of scoring to apply (if the collocation detection is based on association measures) or other selection processes, such as human annotation, part of speech filtering, etc.

Or, just do your analysis in a compounding language such as German where you find words such as _Donaudampfschifffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaft_ and MWEs are not really a problem!! 😃

**Comment by adamlauretig** [comment]
Thanks for the suggestions, @kbenoit, and the thorough explanation of how you structure the task hierarchy in quanteda. 

If I understood you correctly, the below would be an example of what you described (without the word2vec for the moment)? 

Unfortunately, I don't think learning German can solve my current problems 😂 

```R
options(stringsAsFactors = FALSE)
library(quanteda)
library(data.table)
library(stringr)
d <- quanteda::data_corpus_inaugural
tmp_data <- data.table::data.table(txts = d$documents$texts, yr = d$documents$Year, 
  president = paste(d$documents$FirstName, d$documents$President))
tmp_data <- as.data.table(tmp_data)

inaug_tokens <- tokens(x = char_tolower(tmp_data$txts), "word", 
  remove_punct = TRUE, remove_separators = TRUE)
inaug_tokens2 <- tokens_remove(inaug_tokens, stopwords("english"), padding = TRUE)
cols <-  textstat_collocations(inaug_tokens2, size = 2:3, min_count = 2)
combined <- tokens_compound(inaug_tokens, cols)
fcm_inaug <- fcm(combined, context = "window", window = 5)
```

**Comment by kbenoit** [comment]
😱 I don't know what you are doing with data.table there, this is equivalent and much easier (and easier to follow).

``` r
library("quanteda")
## Package version: 1.4.0
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.

toks <- data_corpus_inaugural %>%
  tokens(remove_punct = TRUE) %>%
  tokens_remove(stopwords("english"), padding = TRUE)
colls <- textstat_collocations(toks, size = 2:3, min_count = 2)
tokscomp <- tokens_compound(toks, subset(colls, z >= 2.58))
fcmat <- fcm(tokscomp, context = "window", window = 5)
```
Note that you will probably want to filter the collocations as I have based on scoring (and ideally based on even better criteria) otherwise you are compounding all bigrams and trigrams. And since bigrams are nested inside trigrams, you would want to do this sequentially.

But that's a Stack Overflow question.
