### ISSUE TITLE
What should we do with elision in French texs?

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1610]
Is there anyone who know how to deal with [elision](https://en.wikipedia.org/wiki/Elision_(French)) in French texts? As far as I know, 'le' and 'la' are define articles that can be removed as stopwords, but they often stick to the following word.

I hoped that the ICU has an function to deal with this, but not sure if it is possible:
```r
require(stringi)
stri_split_boundaries(txt_fr, 
                      opts_brkiter = stri_opts_brkiter("word", 
                                                       locale = "fr_FR"))
# [[1]]
# [1] "Ceci"      " "         "est"       " "         "un"        " "         "article"  
# [8] " "         "sur"       " "         "l'Irlande" "."  
```
Applying `tokens_split()` is the only way that I could find to isolate 'l':
```r
require(quanteda)
txt_fr <- c("Ceci est un article sur l'Irlande.")
toks_fr <- tokens(text_fr)
# tokens from 1 document.
# text1 :
# [1] "Ceci"      "est"       "un"        "article"   "sur"       "l'Irlande" "."  
tokens_split(toks_fr, "'")
# tokens from 1 document.
# text1 :
# [1] "Ceci"    "est"     "un"      "article" "sur"     "l"       "Irlande" "."     
```
Is there a better way to do this?

**Comment by ClaudeGrasland** [comment]
French is not an easy language ... But the problem of elision does also exist in English isn't it (is not it) ? I imagine that you have also face the same problem with english grammar forms like < Peter's Friend> ?

I will discuss with colleagues but I guess that the simplest solution is to replace all apostrophs <'> by a blank space < >. Alternative solution is to enumerate with a regular expression all forms that are associated to an apostroph and to remove it. But they are a lot. The most frequent are probably the following ones :
c : <c'est = ceci eest>
d : <d'avoir = de avoir>
j : <j'ai = je avoir>
l': <l'arbre = le arbre ; l'île = la île>
m : <il m'aime = il aime moi>
n : < il n'aime pas = il non aime>
qu : <je crois qu'il dort = je crois que il dort>
s : <il s'est en dormi = il est endormi lui > (reflexive)
t : <je t'ai dit = je ai dit à toi>

The problem is that you destroy important grammar forms if you remove all these forms. For example, if you proceed to a sentiment analysis it is very dangerous to destroy the negative form <n'> and if you want to interpret an action, it is as well dangerous to destroy the marks of reflexive form <s' or m' or t'>.

**Comment by kbenoit** [comment]
In v2, we made it much easier to use the results of external tokenizers to construct a "tokens" object. We also realized that we can never the breadth of multi-language tokenizer needs as well as more specific tokenizers - hence why we now support and encourage specialist tokenizers when needed.

Note: spaCy issues a warning about the lemmas, but they seem to be correct. (The "fr_core_news_sm" model does not do anything with lemmas, so you need the medium one.) See https://spacy.io/models/fr.

``` r
library("spacyr")

# spacy_download_langmodel("fr_core_news_md")
spacy_initialize(model = "fr_core_news_md")
## Found 'spacy_condaenv'. spacyr will use this environment
## successfully initialized (spaCy Version: 2.2.3, language model: fr_core_news_md)
## (python options: type = "condaenv", value = "spacy_condaenv")

sp <- spacy_parse("Je t'ai dit il s'est tué sous l'arbre.")
## Warning in spacy_parse.character("Je t'ai dit il s'est tué sous l'arbre."):
## lemmatization may not work properly in model 'fr_core_news_md'

sp
##    doc_id sentence_id token_id token lemma   pos entity
## 1   text1           1        1    Je    je  PRON       
## 2   text1           1        2    t'    te  PRON       
## 3   text1           1        3    ai avoir   AUX       
## 4   text1           1        4   dit  dire  VERB       
## 5   text1           1        5    il    il  PRON       
## 6   text1           1        6    s'    se  PRON       
## 7   text1           1        7   est  être   AUX       
## 8   text1           1        8   tué  tuer  VERB       
## 9   text1           1        9  sous  sous   ADP       
## 10  text1           1       10    l'    le   DET       
## 11  text1           1       11 arbre arbre  NOUN       
## 12  text1           1       12     .     . PUNCT


library("quanteda", warn.conflicts = FALSE)
## Package version: 2.0.2
## Parallel computing: 2 of 8 threads used.
## See https://quanteda.io for tutorials and examples.
# replace token with lemma
sp$token <- sp$lemma
# now the un-apostrophied tokens are used
as.tokens(sp)
## Tokens consisting of 1 document.
## text1 :
##  [1] "je"    "te"    "avoir" "dire"  "il"    "se"    "être"  "tuer"  "sous" 
## [10] "le"    "arbre" "."
```
