### ISSUE TITLE
docname uniqueness behaviour

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#1611]
* element name is always the "docname": character element name for corpus, list element name for tokens, and rownames for dfm.

* docnames will always be unique

* if a corpus is constructed where the inputs for docnames are not unique, then they will be made unique

* `docid_` is an internal factor recording the document identifer
    - this will become non-unique after `tokens_chunk()`, `corpus_segment()`, or `corpus_reshape()`
    - we will add `corpus(x, ..., unique_docnames = TRUE)` by default to enforce that all docnames will be unique, in which case the docname and `_docid` will be the same.
    - if `corpus(x, ..., unique_docnames = FALSE)` and supplied docnames are not unique, then the docnames will be made unique, but the `docid_` will be non-unique, and `attr(x, "unit")` will be `segments`. This makes a corpus that has been just constructed look like one that has just been segmented. We also would then set `segnum_` to a sequence within `docid_`.

* We remove `docname_` and `docnum_` from docvars since these are not needed.

* Redefine `docnames()<-` and `names()<-` for corpus, tokens, and dfm to enforce the uniqueness behaviour.

**Comment by koheiw** [comment]
I was thinking what is the most robust way to sync `docname_` and element names. One way is to override the functions that change element names such as `row.names()<-` and `rownames()<-` but we cannot rally prevent them from tempering with object attributes, because there is no private/public distinction in variables in R.

So how about letting users to change the element names, but overwrite them by `docname_` every time they intact with the objects? I think this can be done just by adding a few likes in `as.corpus()`, `as.tokens()`, `as.dfm()`.

**Comment by kbenoit** [comment]
Don't we already do this? Maybe I misunderstood the nuance of your suggestion, but I thought we captured that here:

https://github.com/quanteda/quanteda/blob/dev-v2/R/docnames.R#L83-L128

The only way a user can override this is for a dfm, by accessing the `@Dimnames` slot directly. If that is what they want to do, I saw either a) let them, they must be experts and have a very good reason for going this close to the metal, or b) let them and to hell with them for being so foolish if they don't know what they are doing.

**Comment by koheiw** [comment]
My suggestion is to remove 
https://github.com/quanteda/quanteda/blob/dev-v2/R/docnames.R#L83-L128
and change
https://github.com/quanteda/quanteda/blob/dev-v2/R/corpus-methods-quanteda.R#L121-L125
to
```r
as.corpus.corpus <- function(x) {
    attr(x, "names") <- attr(x, "docvars")[["docname_"]]
    if (is_pre2(x))
        x <- upgrade_corpus(x)
    return(x)
}
```
The same in `as.tokens.tokens()` and `as.dfm.dfm()`.

**Comment by kbenoit** [comment]
Then if someone renamed the element names using `names<-()` for a corpus, these would change, and then the first time it was used in a corpus function, the changes would get reverted. That would be frustrating! We might as well just block `names<-.corpus()` then.

But what is wrong with the current approach?

**Comment by koheiw** [comment]
I think it is OK to revert element names, because the user is doing what users should not do.

I think `rownames()`, `rownames()<-`, `names()` and `names()<` are too fundamental to overwrite (I cannot imagine what will happen).  My fear was confirmed when I also saw errors in `docnames<-` in my actual project after some complex operations. I can try to replicate this particular error, but I don't think we can test all possible cases.

**Comment by kbenoit** [comment]
We've rewritten the methods for dfm, tokens, and corpus but these basically pass through the function to the base types, after taking the additional step of syncing the `docname_`. This is the sync operation you suggested in reverse: changing the element names updates the internal names. You are suggesting that the internal objects should update (and automatically override!) the element names.

Your project probably just needs the sort of adaptation to the `dev-v2` that a lot of our code required. (But that branch is passing fine now.) 

If we wanted to override the use of `names<-()` and `docnames<-()` then I think we would need to simply disallow these. It would be baffling to a user to allow the names to change using `base::names<-()` and then undo those changes the first time they pass their object to a **quanteda** function and `as.x.x()` overwrote their changes!
