### ISSUE TITLE
Restore original unit by dfm_group()

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1632]
We are trying to hide system level docvars like `docid_` from users as much as possible in the new corpus object, but they need to run `dfm_group(dfmat, "docid_")` to restore original units (this is probably the only occasion to for users to specify `docid_` manually). Why don't we make it possible to by  `dfm_group(dfmat)`?

**Comment by kbenoit** [comment]
Don't we already have an app for that?
```r
corpus_reshape(x, to = "documents")
```
I think the policy of hiding system variables is a good one. Let's reserve `dfm_group()` for docvars or externally supplied vectors.

**Comment by koheiw** [comment]
Yes, what I am proposing is basically to achieve `dfm_reshape(x, to = "documents")` by `dfm_group()`.

**Comment by kbenoit** [comment]
Is the gain of having to expose an internal variable for `dfm_group(x)` worth whatever benefit exists of being able to do the `corpus_reshape()` a second way? My opinion is that it's not, and that we are better off recommending one (best) way to do things rather than saying there are two ways to do things. 

I'm sure you remember from our many discussions :smile: how we split the formerly overlapping functionality fo `corpus_segment()` and `corpus_reshape()`, so that segment just splits on patterns, and reshape splits on units with a standard definition (sentences, paragraphs, etc). Reshape is really what we want for moving back to single documents, since no one should be manipulating `docid_` (except us!).

**Comment by kbenoit** [comment]
Or here's an alternative: We export this function:

```r
docid <- function(x) {
    get_docvars.corpus(x, field = "docid_", system = TRUE)
}
```
and keep it discreet. People can read the docid, if they really, really want to, using that, e.g.
```r
dfm_group(corp, groups = docid(corp))
```

**Comment by koheiw** [comment]
I had an idea to make `docid()` as a sister of `docnames()`, so it looks fine for me.

By the way, we do not have `dfm_reshape()` yet and `corpus_reshape()` does not work on a DFM.

**Comment by kbenoit** [comment]
True!
