### ISSUE TITLE
Tests are breaking following changes to tidytext sentiment datasets

### ISSUE THREAD

**Issue by juliasilge** [quanteda/quanteda#1705]
Hello, all! I'm the maintainer of tidytext, a package in `Suggests` involved in sentiment data used here in quanteda. We've done a re-examination of the decision to include so many sentiment lexicons within tidytext in juliasilge/tidytext#131, because of how the lexicons have various licenses and tidytext has a *different* license. We've come to the conclusion that it was a mistake on our part to include lexicons like the NRC and Loughran datasets under our MIT license. We've moved these datasets out of tidytext and access is now available in a [separate new package](https://github.com/EmilHvitfeldt/textdata) that provides infrastructure for downloading these, with the user agreeing to the terms of the license. Unfortunately, while this change still allows for use in analyses, it makes it more difficult to use these sentiment lexicons in packages or vignettes. 😕

The sentiment lexicon of Bing Liu and collaborators (`get_sentiments("bing")`) is still in tidytext, because those creators have given specific permission for us to include it.

This new version of tidytext is going to be submitted to CRAN in about a week or so, and after that the Bing lexicon will be the only one available directly in tidytext. I want to a) let you know so you can work on updates and b) apologize for how this chain of decisions impacts you! Let me know if you have questions or if I can help.

**Comment by kbenoit** [comment]
Thanks @juliasilge we will make that change. 

We have a package [**quanteda.dictionaries**](https://github.com/kbenoit/quanteda.dictionaries) that also has a number of dictionaries for text analysis, in the quanteda format, but this remains GitHub-only in my personal repo thus far, because we have not cleared permissions yet from all of the dictionary authors.

Speaking of licenses, I don’t think that you can make **tidytext** MIT if it includes GPL software - and for instance the **Matrix** package and **stringr** are both GPL. GPL software can include MIT license components but if software includes GPL components, it also must be GPL. Which is why most stuff built on R is (and must be) GPL. I wish I were wrong on this and would be happy to be proven wrong though! And I know that it does not help with this issue but rather makes it more complicated.

**Comment by kbenoit** [comment]
Note to selves: Time to implement those changes, following the usual CRAN warning email.

https://cran.r-project.org/web/checks/check_results_quanteda.html
