### ISSUE TITLE
Improve re-export method for stopwords

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1850]
```r
#' @section Stopwords: 
#' 
#' Stopword lists were formerly built into \pkg{quanteda}, but have been moved to the 
#' \pkg{stopwords} package. See [stopwords::stopwords()].
#' @importFrom stopwords stopwords
#' @name stopwords
#' @inherit stopwords::stopwords
#' @export 
NULL
```

**Comment by kbenoit** [comment]
What's wrong with this? It's exactly how we should be encouraging other packages to import `stopwords::stopwords()` instead of including their own functions and copy (e.g. like **tm** still does).

I think we should add something like `usethis::use_pipe()` to the **stopwords** package but call it `use_stopwords()` to achieve a similar effect.
