### ISSUE TITLE
add an remove apostrophe option to the tokenizer

### ISSUE THREAD

**Issue by xiaoouwang** [quanteda/quanteda#1863]
## Requested feature

This option is very useful especially in languages like French where apostrophes are prevailing and aren't necessarily related to grammatical markers as in English. It seems to me that there is no easy way to configure this behaviour with quanteda's tokenizer

Please explain the feature you want clearly and concisely. If possible, please add example output.

```r
tokens("c'est",
  what = "word",
  remove_apostro = TRUE,
# output is ("c", "est")
```

## Use case

Please describe situations in which the requested feature will be useful.

## Additional context

Please add any other information about the feature request.

**Comment by kbenoit** [comment]
The best way to deal with this issue would be to use a better (smarter) tokenizer trained on a French language model. In forthcoming quanteda v2, we are further separating the "tokenization" function of token segmentation from the `tokens()` constructor. But it's already possible in v1.5.2 using **spacyr**, which has a language model for French.

This is smarter because it differentiates contractions from apostrophes.

``` r
library("quanteda")
## Package version: 1.5.2

library("spacyr")
# spacy_download_langmodel(model = "fr")
spacy_initialize(model = "fr")
## Found 'spacy_condaenv'. spacyr will use this environment
## successfully initialized (spaCy Version: 2.1.4, language model: fr)
## (python options: type = "condaenv", value = "spacy_condaenv")

txt <- "C'est vrai qu'on aime quanteda."
spacy_tokenize(txt) %>%
  as.tokens()
## tokens from 1 document.
## text1 :
## [1] "C'"       "est"      "vrai"     "qu'"      "on"       "aime"     "quanteda"
## [8] "."
```

If you want the apostrophes removed, simply do this prior to constructing the tokens:
```r
spacy_tokenize(txt) %>%
  lapply(stringi::stri_replace_all_fixed, "'", "") %>%
  as.tokens()
## tokens from 1 document.
## text1 :
## [1] "C"        "est"      "vrai"     "qu"       "on"       "aime"     "quanteda"
## [8] "."
```
