### ISSUE TITLE
Whitespace error for stemming when constructing a dfm

### ISSUE THREAD

**Issue by GregoryEady** [quanteda/quanteda#1934]
I'm tokenizing data from Tweets and run into an error removing whitespace, where there is presumably a special character that looks like a space that isn't being removed. In the first case, the "space" is treated as if it is a normal character and thus doesn't get split. In the second case, I removed the "space" and put a normal space and it separates as expected. Hopefully this will come through with a copy and paste on GitHub. Although the two commands look identical, the strings are not.

```
> tokens("in @usaidffp")
tokens from 1 document.
text1 :
[1] "in @usaidffp"

> tokens("in @usaidffp")
tokens from 1 document.
text1 :
[1] "in"        "@usaidffp"

> "in @usaidffp" == "in @usaidffp"
[1] FALSE
```

**Comment by kbenoit** [comment]
Thanks for finding this. The problem is that in the first text, the two tokens are separated by U+202F, a "NARROW NO-BREAK SPACE". (Unfortunately) these appear in the RStudio editor as a red centre dot on a pink background, when you type alt/option-SPACE.

Grabbing a screen shot from my editor:
<img width="561" alt="Screenshot 2020-04-22 14 23 44" src="https://user-images.githubusercontent.com/2182246/79987314-23019d00-84a5-11ea-8ffe-d383999e225a.png">

@koheiw it works when there is a non-word character starting a token, but not with our special character "က001က01us". 

So while we need to fix this - probably by just replacing these with a regular space, or by updating the **stringi** rules - here's a workaround to clean up your text: `stri_replace_all_fixed(x, "\u202F", " ")`. You can see here that it works (although you cannot see the "\u202F" when I include it this way:
```r
> x <- "one two"
> stri_replace_all_fixed(x, "\u202F", " ") %>%
+     stri_split_boundaries(type = "word")
[[1]]
[1] "one" " "   "two"
```

**Comment by kbenoit** [comment]
Note: I filed https://github.com/gagolews/stringi/issues/377

**Comment by koheiw** [comment]
Closed. See #1935
