### ISSUE TITLE
Separate core function to different package

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#1993]
For #1991 , I have created [**quanteda.core**](https://github.com/koheiw/quanteda.core) keeping corpus, tokens, and dfm functions and textstat functions that requires C++ files. I want to make the core package even smaller, but it is a start.

As always, S4 objects created by **quanteda** caused problems because R looks for the package when they are loaded. We  cannot do anything with old S4 objects, but R should call methods in **quanteda.core** if quanteda::dfm and quanteda::dictionary2 inherit quanteda.core::dfm and quanteda.core::dictionary2 respectively.

**Comment by kbenoit** [comment]
I think it's time for an extended planning discussion of the evolving ecosystem, including devolution/partitioning. I'd suggest agreeing on that before we invest too much time into implementing it.

Unless this is very incremental, this is probably a v3 move. We split **quanteda.textmodels** with the v2 release, and it still causes the occasional headache. With this move, I see nightmares ahead with `revdepcheck()`...

Issues:

* What do we do with the original package **quanteda**? If the core functions get moved to **quanteda.core** or (**quanteda.nlp**) then **quanteda** could become a wrapper to load the various packages, like **tidyverse**. My preference is for doing this split primarily to ease maintenance and testing, rather than appearing to offer standalone pieces. It also helps extendability, since the **quanteda.core/nlp** could offer a nice platform for other text-based packages to build on, without the overhead of all of our analytic functions which they might not need.

* What is the structure of dependency? Do we use Imports, or Depends? In other words should a module package be able to be run standalone, or will it always require **quanteda.core** being loaded? In **quanteda.tidy** for instance, there is no requirement to load **dplyr** or any **tidyverse** packages, I just import them all. **quanteda.textmodels** actually works without having **quanteda** loaded, although you have to load it in order to use any **quanteda** function calls.

and of course:

* What are the optimal boundary lines for the splitting? I think we should map this carefully and do it once with an eye to a v3 release. We don't want to spend too much time maintaining parallel versions as we did in developing v2, but we want to start developing now with an eye to facilitating the split. And we want a model that requires no future splits, but makes it clear what would be added to core and what to a module package.

**Comment by koheiw** [comment]
My rough idea about the dependency structure is the following:

- quanteda
   - Contain own beginner friendly functions (R)
   - Depends on quanteda.textplot (R)
   - Depends on quanteda.textstat (R and C++; difficult to split)
   - Depends on quanteda.core (R and C++)
- quanteda.textmodel 
   - Contains own textmodel functions (R and C++)
   - Imports quanteda.core
- quanteda.sentiment (R)
   - Contains own analytic functions
   - Imports quanteda.core
- newsmap (R)
   - Contains own analytic functions
   - Imports quanteda.core
- Other texts packages 
   - Depends on or Imports quanteda.core

As far as quanteda depends on quanteda.textplot, quanteda.texstat and quanteda.core, current users will not notice that they are different packages under one roof.

**Comment by kbenoit** [comment]
OK, so that differs from our current structure really only by separating the `textstat_*()` and `textplot_*()` functions into a new **quanteda.textstat** package. What about that as a next step? **quanteda** then becomes what you are calling **quanteda.core** since there is not much else we could separate from it. I don't think we could remove dictionaries and the lookup functions since they are so integrated into the core package, such as via `pattern`.

**quanteda.textstat** would include:
- Everything under https://quanteda.io/reference/index.html#section-text-statistics except `topfeatures()` and `sparsity()`. (We might need to retain `textstat_summary()` internally in the core package though.)
- `textplot_keyness()` and `textplot_wordcloud.keyness()`, since these work only on the results of `textstat_keyness()`. This is similar to having moved `textplot_scale1d()` to **quanteda.textmodels** since it only works on objects created by functions in those packages. 
- To be consistent however we would retain the other `textplot_*()` functions (xray, wordcloud - for the generic and the dfm - and network) since these operate directly on core quanteda objects such as a kwic, dfm, or fcm.

**Comment by koheiw** [comment]
**quanteda** will remain the largest toolkit that imports (and reexports) all the `textstat_`, `textplot_`, and other convenient/legacy functions (`dictionary_edit`, `corpus_trimsentences`, `bootstrap_dfm`, etc.). **quanteda.core** will have `dfm_*`, `tokens_`, `corpus_*` and `dictionary()` because the share many R and C++ code. You can see what I consider core functions in https://github.com/koheiw/quanteda.core/tree/master/R

I want to separate plotting functions in `quanteda.textplot` because there are **ggplot2** enthusiasts who might lead the development of the package (plotting functions are very different from other functions because it turns data into the long format, requiring **reshape** etc.). We also have to reconsider the design of plotting functions because there is not reason to have functions that only works on one type of object: `textplot_keyness` could be just a `textplot_scale1d.textstat_keyness` or `textplot.textstat_keyness`.
