### ISSUE TITLE
plot of term frequencies vs docvars

### ISSUE THREAD

**Issue by adamobeng** [quanteda/quanteda#201]
e.g. [here](http://www.nltk.org/images/inaugural2.png)

**Comment by adamobeng** [comment]
This work has begun in [the dev_plots branch](https://github.com/kbenoit/quanteda/tree/dev_plots).

@kbenoit What would you say is the best interface is to these new methods? Should we rely on plot method dispatch with a plot type parameter? What about those plots which could plausibly be constructed from multiple different types of object?

**Comment by kbenoit** [comment]
Good topic for a design-athon meeting. My view is that we only want plots that are natural extensions of an object in order to understand that object. This clearly includes a word cloud, for instance, but might exclude a "term frequency by docvar" plot which is something that we make easy enough for a user to implement on his/her own.

Take a look at both the `qdap` and `zipfR` packages, since they implement some of what you have suggested.

**Comment by adamobeng** [comment]
For our purposes, interfacing with the zipfR plotting methods doesn't get us much above using ggplot2, qdap's plotting of an adjacency matrix uses igraph, which we could just do anyway.

**Comment by adamobeng** [comment]
Implemented in [PR 205](https://github.com/kbenoit/quanteda/pull/205)
