### ISSUE TITLE
Candidates to removed in v3.0

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2022]
List of functions and arguments that could be removed in v3.0.

- `char_select()`
- `char_segment()`
- `add_summary_metadata()`
- `texts(groups = NULL)`
- `topfeatures(groups = NULL)`: use `textstat_frequency()`
- `as.corpus.corpuszip()`
- `corpus_trim()`
- `char_trim()`
- `corpus_trimsentences()`
- `convert()` 
- `tokens_skipgrams()`
- `tokens_keep()`
- `dfm_keep()`

More will be added to the list...

**Comment by kbenoit** [comment]
We can do some trimming but it should be motivated by a desire to 
a) remove functions that are deprecated or no longer used - these should all be killed from v3.0; and
b) achieve greater consistency with other functions and the design of the package as a whole.

The desire for stark minimalism for its own sake is not as compelling for me, since we can always turn off the functions from appearing in the package index, and having 4-5 extra functions does not affect performance, but can be very useful.

We also have to consider carefully the effects on existing code, in:
- extension packages possibly not yet on CRAN;
- the by now extensive set of StackOverflow answers that might use them;
- various instructors' code for teaching.

My take:

**Definitely can remove:**
- `as.corpus.corpuszip()`. This was used only when we created the ill-fated "compressed" corpus that never really worked.

**Definitely should not remove:**
- `convert()`.  This is used all the time, and scattered all over StackOverflow and in teaching examples. It's a critical, centralized method for handing off dfm objects to other functions, especially for machine learning.


**Maybe could be remove** - Ken to review other package usage to see if these could be moved out - but doing very little harm to anything by being included and not showing up in the package index:
- `add_summary_metadata()`.
- `corpus_trim()`. This is used in `textstat_readability()` and is also part of the **sophistication** package that is necessary for replicating my 2019 _AJPS_ paper results. It could be moved to that package, but I still think it's quite useful, for removing things that are really short, or that follow specific patterns such as the cruft resulting from pdf conversion (like footers). This is something that involves cleaning up junk from a corpus before it's saved as a "clean" starting point, rather than manipulating corpus data the way the other functions do.

**Primarily design choices** : Depending on our philosophy of supporting `char_*()` functions.  I actually really like that we support these, since it gives a continuity across types and provides some worker functions for lower-level calls in our other methods, as well as functions for direct manipulation of character vectors. This is used in some of the dictionary packages a lot, for instance. 
- `char_select()`.  Note that we just added this in 2.1! https://github.com/quanteda/quanteda/pull/1925, a PR that you reviewed and approved. I like this function, since it provides a method for selecting character items consistent with the rest of our package functions, providing for instance glob selection.
- `char_segment()`. This is also useful. But you have always disliked the `corpus_segment()` too, while I find it incredibly useful. Is this an issue of wanting to remove `char_*()` functions or a way to start removing the segment functionality altogether?

**Unsure:**
- `texts(groups = NULL)`.  Not sure what you want to remove here - `texts.character()` or `texts()` altogether? This function is widely used as a way to get texts from our objects, without modifying the objects or needing to know their internal structure. This used to be really important when a corpus was not an overclassed `character`, and while `as.character()` works now, this might not always be the case. The `groups()` is also useful. What's the benefit of removing it?

**Comment by koheiw** [comment]
Please wait for a while. The list is still a draft.

**Comment by kbenoit** [comment]
Moved to the spreadsheet and ongoing discussion.
