### ISSUE TITLE
do.call() in deprecation code breaks internal calls in other packages

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2077]
When quanteda is not loaded, do.call cannot find `tokens()`.
```
── Error (test-as.textmodel.R:5:1): (code run outside of `test_that()`) ────────
Error: error in evaluating the argument 'x' in selecting a method for function 'as.list': could not find function "tokens"
Backtrace:
     █
  1. ├─utils::head(...) test-as.textmodel.R:5:0
  2. ├─LSX::char_keyness(toks_test, "america*", min_count = 1, p = 0.05)
  3. │ └─LSX::char_context(...)
  4. │   └─LSX::textstat_context(...)
  5. │     ├─quanteda::dfm(y, remove = "")
  6. │     └─quanteda:::dfm.tokens(y, remove = "") /home/kohei/repo/quanteda/R/dfm.R:53:4
  7. │       ├─names(otherargs) %in% names(as.list(args("tokens"))) /home/kohei/repo/quanteda/R/dfm.R:103:4
  8. │       ├─base::as.list(args("tokens")) /home/kohei/repo/quanteda/R/dfm.R:103:4
  9. │       └─base::args("tokens") /home/kohei/repo/quanteda/R/dfm.R:103:4
 10. └─base::.handleSimpleError(...)
 11.   └─base:::h(simpleError(msg, call))
```
It is probably better to avoid using `do.call()` whenever possible. I don't see any reason to use the function:.

https://github.com/quanteda/quanteda/blob/50d7df9fa1fd89bc0ac7f64320dcc494692cef7e/R/dfm.R#L144-L148

It is better to define an internal function to trap  `...` in a more reliable and concise manner:
https://github.com/quanteda/quanteda/blob/50d7df9fa1fd89bc0ac7f64320dcc494692cef7e/R/dfm.R#L102-L108

For example,
```r
deprecate_dots <- function(x, ...) {
    if (length(list(...))) {
        .Deprecated(msg = "'...' should not be used for tokens() arguments; use 'tokens()' first.")
        x <- tokens(x, ...)
    }
    return(x)
}
```

**Comment by kbenoit** [comment]
It's fixed in #2075, see f0118f3

**Comment by koheiw** [comment]
That is a quick and dirty fix. Why do you use `do.call()` in the fist place?

**Comment by kbenoit** [comment]
This discussion should take place in #2075.

What's dirty about it? We need to separate the arguments to `tokens()` formerly passed via `...` - this is `otherargs_tokens` - from the now removed, formerly explicit `dfm()` arguments that we are deprecating (`otherargs`).

```r
x <- do.call(tokens, c(list(x = x), otherargs_tokens))
```
converts the character/corpus `x` into tokens and passes the `otherargs_tokens` as arguments. Then further along, we deal with the deprecated other arguments in `otherargs`.

We will remove all this code when we get to v4!

**Comment by kbenoit** [comment]
Solved in #2075.

**Comment by koheiw** [comment]
My understanding of `do.call()` that we should not be used for serious purposes as it looks at the different environment (this is why you need `quanteda::`) from where it is placed. I am trying to make v3 more reliable for system/package development but use of `do.call()` is an opposite direction. I approved the PR because I though the deprecation code will go away soon, but it was my mistake as it will stay for a year or more probably.

I also found a worrying note in the manual.

> The behavior of some functions, such as substitute, will not be the same for functions evaluated using do.call as if they were evaluated from the interpreter. The precise semantics are currently undefined and subject to change.

**Comment by koheiw** [comment]
I also think that, if hiding the arguments make the code so messy and dirty, it is better to keep them visible and simply raise warnings.

**Comment by kbenoit** [comment]
There's absolutely nothing wrong with `do.call()` used the way that we do, since we only work within the function environment for the call. We're not using substitute / eval or anything like that for those functions. `do.call(fun, args)` without changing the default `envir = parent.frame()` is the same as `fun(args)`. We use `do.call()` in `msg()` for instance. We are not doing anything with the environment scope here.

The thing that broke the other packages is fixed in 
https://github.com/quanteda/quanteda/blob/9a9487bbf89ab65b9260cff26a4d6ad94f5a75d2/R/dfm.R#L104, and it had nothing to do with `do.call()`. Rather, it was the call to get the list of `tokens()` arguments. This required `tokens` to be accessible and without the `quanteda::tokens`, if **quanteda** was not attached, then this was not found. Any package calling `dfm()` would of course need to have **quanteda** as an import, so it was available, but just needed explicit reference.

If you can show me any way that this makes v3 less reliable, I'll share your concern, but I don't think it does in #2075 (and I've run a full revdepcheck on all of the other packages, where `dfm()` is one of the most commonly called functions).

**Comment by koheiw** [comment]
You can stick with your code but I will probably fork the package and remove all the `do.call()` for my own use because I do not trust `dfm()` any longer.
