### ISSUE TITLE
Easier way to subsetting objects by ntoken

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2237]
I have been thinking about an easier way to subset objects by ntoken. Currently, there is only one way to do it.

```r
require(quanteda)
corp <- data_corpus_inaugural |>
    corpus_reshape()
 
toks <- tokens(corp) |>
    tokens_remove(stopwords()) 
toks <- tokens_subset(toks, ntoken(toks) > 10)
```

How about allowing `tokens_subset(toks, ntoken_ > 10)`, which is similar to `tokens_subset(toks, segid_ == 1)`? This is especially useful when we use pipes.

```r
toks <- tokens(corp) |>
    tokens_remove(stopwords()) |>
    tokens_subset(toks, ntoken_ > 10)
```
We can implement this just by adding `ntoken_` as a system-level document variable, which can be extracted by `docvars(toks, system = TRUE)`. If we want to do the same with corpus, the name of the variable would be `length_` or `n_` to include both `ntokens` and `nchar`.

**Comment by kbenoit** [comment]
Wouldn't this require recomputing and updating these system docvars each time the object was subsetted or ['d? What if a user circumvented these?

These functions are super fast, e.g. `lengths()` for tokens, `length()` for corpus, so it's not a problem to compute them each time, but I agree the syntax is a bit cumbersome.

What about having some special functions like `.SD` in data.table, so that `.ntoken` referred to the tokens in `x` and was computed on the fly? so:

```r
toks <- tokens(corp) |>
    tokens_remove(stopwords()) |>
    tokens_subset(.ntoken > 10)
```

and this triggers the `ntoken(x)` code inside the function?

**Comment by koheiw** [comment]
I don't like how data.table works much. I thought adding a docvar is best for the `*_subset` but we can add `min_ntoken` and `max_ntoken` arguments like `*_trim()`.

**Comment by kbenoit** [comment]
It's a bit more like **magrittr's** use of `.` than **data.table**'s use of functions like `.SD()`, since we don't need a function, but rather a reference to the `x`, like **magrittr**.

So for functions that would operate on `x`, we could just use `.ntoken`, `.min_ntoken`, etc as part of the logical. Then we evaluate the expression by calling the function or argument on `x`. This is also simpler than cacheing elements like the number of tokens and trying to keep it updated.

**Comment by koheiw** [comment]
The easiest way to implement this seems to create a variable temporarily. Since `ntoken()` cost very little, it does not make sense to save `ntoken_` as a internal document variable. I wonder if there are other special variables that we can create and use to subset documents... If there aren't any, adding `min_ntoken` and `max_ntoken` arguments would be a better approach.

```r
tokens_subset.tokens <- function(x, subset, drop_docid = TRUE, ...) {
    
    x <- as.tokens(x)
    check_dots(...)
    
    attrs <- attributes(x)
    docvar <- get_docvars(x, user = TRUE, system = TRUE)
    docvar[["ntoken_"]] <- ntoken(x) # temporary variable
    r <- if (missing(subset)) {
        rep_len(TRUE, ndoc(x))
    } else {
        e <- substitute(subset)
        r <- eval(e, docvar, parent.frame())
        r & !is.na(r)
    }
    return(x[r, drop_docid = drop_docid])
}
```

``` r
require(quanteda)
corp <- data_corpus_inaugural
toks <- tokens(corp)
ndoc(toks)
#> [1] 59
ndoc(tokens_subset(toks, ntoken_ > 2000))
#> [1] 33
```
