### ISSUE TITLE
Tidy up vignettes

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda#2256]
In relation to #2248,

- Deprecated arguments and functions should be be used.
- Following the naming convention in examples and the tutorials
    - `comp_toks` and `toksComp` should be `toks_comp`
- Remove articles that are not attracting visitors (see Google Analytics)

**Comment by koheiw** [comment]
@stefan-mueller can you do?

**Comment by stefan-mueller** [comment]
Yes, I can take care of it – this or next week. Happy to go through all vignettes, update deprecated functions/workflows, and follow the **quanteda** naming conventions in all vignettes.

I would suggest removing the [feature comparison](https://quanteda.io/articles/pkgdown/comparison.html) which is outdated and difficult to maintain.

**Comment by kbenoit** [comment]
Agreed on the feature comparison.

**Comment by stefan-mueller** [comment]
I have tidied up the vignettes in the branch [**fix-pkgdown**](https://github.com/quanteda/quanteda/tree/fix-pkgdown). 
You see the changes in my commits, but, generally speaking,  I
1. Applied the **quanteda** [style guide](https://github.com/quanteda/quanteda/wiki/Style-guide) in all the vignettes (except for the replications where we follow the original object names)
2. Used the base R pipe (`|>`) 
3. Rewrote some of the code to make it more readable and comparable with the *quanteda* documentation
4. Corrected links to other vignettes and updated the drop-down menus for the website

Feel free to review and rebuild the pkgdown website, @kbenoit . 

A few issues that need to be resolved/discussed:

- [ ] The dendrogram in the [Quick Start Guide](https://quanteda.io/articles/quickstart.html) does not appear correctly
- [ ] Should we machine translate the updated English Quick Start Guide to other languages rather than fixing issues in each vignette?

**Comment by kbenoit** [comment]
This is great @stefan-mueller, thanks. Did you base this off of the post-merge of #2255 ? I made some changes in there to the menu structure of the site.

**Comment by kbenoit** [comment]
I like the idea of machine translation. ChatGPT?

**Comment by stefan-mueller** [comment]
Yes, it relies on the post-merge of #2255 from this morning, @kbenoit. The feature comparison still appeared in the dropdown menu. Happy to use ChatGPT for the machine translation of the texts. I can take care of this next week.

We might also consider replacing `%>%` with the base R pipe (`|>`) across the entire package documentation. What do you think?

**Comment by kbenoit** [comment]
I am totally for using the new pipe. @koheiw ?

**Comment by koheiw** [comment]
I am fine with `|>` users of old R can substitute it with `%>%` themselves.
