### ISSUE TITLE
UBSAN issues on CRAN from tbb

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2281]
Not our issue it seems, but something [CRAN is complaining](https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/quanteda/00check.log) about. The solution recommended by @kevinushey seems to be to set this in `testthat.R`:

```r
Sys.setenv(RCPP_PARALLEL_BACKEND = "tinythread")
```

See also https://github.com/RcppCore/RcppParallel/issues/169#issuecomment-831715824, see also #1200, #1916.

@koheiw shall I try this, and resubmit? Do you think this has anything to do with recent changes such as https://github.com/quanteda/quanteda/commit/aef22b23a1de4ab1e9b1f7454bc36d41d5009ad1 ?

**Comment by koheiw** [comment]
I don't think `Sys.setenv(RCPP_PARALLEL_BACKEND = "tinythread")` will have any effect, because I am using TBB header directly. **PcppParallel** is just a header only library for us. It is unlikely that https://github.com/quanteda/quanteda/commit/aef22b23a1de4ab1e9b1f7454bc36d41d5009ad1 caused the problem.

**Comment by kbenoit** [comment]
CRAN seems to have accepted it a day after I got the warning, without me replying, so it might have been an issue with their devel platforrm 

```
* using R Under development (unstable) (2023-05-06 r84400)
* using platform: x86_64-pc-linux-gnu (64-bit)
```

Anyway 3.3.1 is up.
