### ISSUE TITLE
Homebrew installation of TBB still not found on macOS when compiling

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#2367]
When compiling from source, even after 

```
brew install TBB
```

I get
```
   checking for tbb/tbb.h... no
   configure: WARNING: parallel computing is disabled because tbb/tbb.h (Intel TBB) is not found
```

hence
```
> library("quanteda")
Package version: 4.0.0
Unicode version: 14.0
ICU version: 71.1
Parallel computing: disabled
See https://quanteda.io for tutorials and examples.
```

**Comment by koheiw** [comment]
I cannot do more than Googling because I don't have a Mac... It is likely that the include path needs to be specified on the platform:

https://stackoverflow.com/questions/72268423/tbb-library-cannot-be-found-cmake-on-macos
https://apple.stackexchange.com/questions/40704/homebrew-installed-libraries-how-do-i-use-them

You can test by making `Makevars` manually and add something like `PKG_CXXFLAGS = -I../inst/include -DTBB` (this is for Windows). `-DTBB` forces to use TBB so compilation should fail when the library is not found.
