### ISSUE TITLE
Design a general corpus object structure

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda#373]
Currently:

*  `corpus`: has a `$documents` data.frame with the first column being `texts`.  
*  `corpuszip`: has a `$documents` data.frame without texts, but has a separate `$texts` vector and a separate `docnames` vector, which is partially redundant. This is necessary in order to compress the `$texts` a vector in memory.

If we generalise the object by separating the `$texts` and linking this through a key to the `$documents` data.frame, then we have more flexibility in making the corpus more flexible, to allow future types such as SQLite. 

We should also think about having the corpus pre-tokenised and possibly tagged.

**Comment by koheiw** [comment]
I think we should base our corpus object on `corpuszip` which stores texts separately. There are different candidate for keeping the text data off memory
- RSQLite
- fst (http://www.fstpackage.org/)
- feather (https://blog.rstudio.com/2016/03/29/feather/)

**Comment by kbenoit** [comment]
All good options - this will be fun to extend.

**Comment by koheiw** [comment]
Corpus object certainly needs complete overhaul as I face docvar related issue almost every day.

There are two separate issues:
- Efficiently storage of original texts using compression and off-memory data stracture
- Consistent handling of user and system docvars across corpus, tokens, and dfm objects

The second problem is getting bigger as docvars are so inconsistent, being an empty data.frame, a data.frame with zero columns with `ndoc = nrow`, or NULL. It should always be data.frame with system variables with `ndoc = nrow`.

This inconsistency is caused by `tokens.character()` that does not return docvars. It should always call `corpus` internally to return docvars:
```r
tokens.character <- function(x) {
     tokens(corpus(x))
}
```
but `corpus.character()` is also messy at the moment. The problem is very deep...

**Comment by kbenoit** [comment]
Certainly we can implement that change for `tokens.character()` - go ahead and push to this branch if you want. I agree on the deeper cleaning of the corpus.R code, but let's put that aside for now, on a list with a cleanup of tokens.R and dfm.R. When we strip out the older code we can do this cleanup at the same time.

**Comment by koheiw** [comment]
OK. I will only make changes in `tokens.R` and leave others for now.
